package charts

import (
	"sort"
	"strconv"
	"strings"

	"github.com/pskshksh/pod-go-helm-factory/sdk/render"
)

const (
	// Chart.yaml
	CHART_API_VERSION = "v2"
	CHART_TYPE        = "application"

	// values.yaml defaults
	DEFAULT_REPLICAS    = 1
	DEFAULT_PULL_POLICY = "IfNotPresent"
	DEFAULT_CPU_REQUEST = "50m"
	DEFAULT_MEM_REQUEST = "64Mi"
	DEFAULT_CPU_LIMIT   = "500m"
	DEFAULT_MEM_LIMIT   = "256Mi"

	// Security defaults. The container runs as this non-root UID/GID unless a
	// descriptor later overrides it. Zero would be root, so this must be non-zero.
	DEFAULT_RUN_AS_UID = 10001

	// Container/probe defaults.
	DEFAULT_PORT           = 8080
	DEFAULT_LIVENESS_PATH  = "/healthz"
	DEFAULT_READINESS_PATH = "/readyz"

	// Service default. The ClusterIP Service listens here and targets the
	// container's named "http" port, so this can differ from the container port.
	DEFAULT_SERVICE_PORT = 80

	// Deployment rollout strategies.
	STRATEGY_ROLLING  = "RollingUpdate"
	STRATEGY_RECREATE = "Recreate"

	// _helpers.tpl substitution placeholders
	PLACEHOLDER_NAME     = "NAME"
	PLACEHOLDER_SELECTOR = "SELECTOR"

	// HELPERS_TEMPLATE is the templates/_helpers.tpl body. PLACEHOLDER_NAME and
	// PLACEHOLDER_SELECTOR are substituted per chart by helpersTPL.
	HELPERS_TEMPLATE = `{{/* Generated by pod-go-helm-factory. DO NOT EDIT. */}}

{{- define "NAME.name" -}}
NAME
{{- end -}}

{{- define "NAME.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name "NAME" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "NAME.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "NAME.labels" -}}
helm.sh/chart: {{ include "NAME.chart" . }}
{{ include "NAME.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- end -}}

{{- define "NAME.selectorLabels" -}}
SELECTOR
{{- end -}}
`
)

// Kubernetes apiVersions and kinds emitted by the templates.
const (
	API_APPS_V1 = "apps/v1"
	API_CORE_V1 = "v1"

	API_NETWORKING_V1  = "networking.k8s.io/v1"
	API_POLICY_V1      = "policy/v1"
	API_AUTOSCALING_V2 = "autoscaling/v2"

	KIND_DEPLOYMENT     = "Deployment"
	KIND_SERVICE        = "Service"
	KIND_SERVICEACCOUNT = "ServiceAccount"
	KIND_NETWORKPOLICY  = "NetworkPolicy"
	KIND_PDB            = "PodDisruptionBudget"
	KIND_HPA            = "HorizontalPodAutoscaler"
)

// Repeated manifest literal values.
const (
	SERVICE_TYPE_CLUSTERIP  = "ClusterIP"
	SECCOMP_RUNTIME_DEFAULT = "RuntimeDefault"
	PORT_NAME_HTTP          = "http"
	PROTOCOL_TCP            = "TCP"
	PROTOCOL_UDP            = "UDP"
	CAP_ALL                 = "ALL"
	TMP_VOLUME_NAME         = "tmp"
	TMP_MOUNT_PATH          = "/tmp"

	// NetworkPolicy.
	POLICY_TYPE_INGRESS = "Ingress"
	POLICY_TYPE_EGRESS  = "Egress"
	DNS_PORT            = 53

	// PodDisruptionBudget default: keep at least one pod during disruptions.
	DEFAULT_MIN_AVAILABLE = "1"

	// HorizontalPodAutoscaler.
	METRIC_TYPE_RESOURCE    = "Resource"
	HPA_TARGET_UTILIZATION  = "Utilization"
	RESOURCE_CPU            = "cpu"
	RESOURCE_MEMORY         = "memory"
	DEFAULT_MIN_REPLICAS    = 1
	DEFAULT_CPU_UTILIZATION = 80
)

// YAML keys. Named so a key is written once and reused everywhere it appears,
// keeping the generated manifests consistent and typo-proof.
const (
	// Chart / metadata.
	KEY_API_VERSION = "apiVersion"
	KEY_KIND        = "kind"
	KEY_METADATA    = "metadata"
	KEY_NAME        = "name"
	KEY_LABELS      = "labels"
	KEY_DESCRIPTION = "description"
	KEY_VERSION     = "version"
	KEY_APP_VERSION = "appVersion"

	// values.yaml surface.
	KEY_REPLICA_COUNT      = "replicaCount"
	KEY_IMAGE              = "image"
	KEY_REPOSITORY         = "repository"
	KEY_TAG                = "tag"
	KEY_PULL_POLICY        = "pullPolicy"
	KEY_IMAGE_PULL_SECRETS = "imagePullSecrets"
	KEY_RESOURCES          = "resources"
	KEY_REQUESTS           = "requests"
	KEY_LIMITS             = "limits"
	KEY_CPU                = "cpu"
	KEY_MEMORY             = "memory"
	KEY_POD_ANNOTATIONS    = "podAnnotations"
	KEY_NODE_SELECTOR      = "nodeSelector"
	KEY_TOLERATIONS        = "tolerations"
	KEY_AFFINITY           = "affinity"

	// Deployment / pod spec.
	KEY_SPEC               = "spec"
	KEY_REPLICAS           = "replicas"
	KEY_STRATEGY           = "strategy"
	KEY_TYPE               = "type"
	KEY_SELECTOR           = "selector"
	KEY_MATCH_LABELS       = "matchLabels"
	KEY_TEMPLATE           = "template"
	KEY_ANNOTATIONS        = "annotations"
	KEY_SERVICE_ACCOUNT    = "serviceAccountName"
	KEY_AUTOMOUNT_SA_TOKEN = "automountServiceAccountToken"
	KEY_CONTAINERS         = "containers"
	KEY_IMAGE_PULL_POLICY  = "imagePullPolicy"
	KEY_VOLUMES            = "volumes"
	KEY_EMPTY_DIR          = "emptyDir"

	// Container.
	KEY_ENV             = "env"
	KEY_VALUE           = "value"
	KEY_ENV_FROM        = "envFrom"
	KEY_SECRET_REF      = "secretRef"
	KEY_CONFIGMAP_REF   = "configMapRef"
	KEY_PORTS           = "ports"
	KEY_CONTAINER_PORT  = "containerPort"
	KEY_PROTOCOL        = "protocol"
	KEY_LIVENESS_PROBE  = "livenessProbe"
	KEY_READINESS_PROBE = "readinessProbe"
	KEY_HTTP_GET        = "httpGet"
	KEY_PATH            = "path"
	KEY_PORT            = "port"
	KEY_TARGET_PORT     = "targetPort"
	KEY_VOLUME_MOUNTS   = "volumeMounts"
	KEY_MOUNT_PATH      = "mountPath"

	// NetworkPolicy.
	KEY_POD_SELECTOR       = "podSelector"
	KEY_NAMESPACE_SELECTOR = "namespaceSelector"
	KEY_POLICY_TYPES       = "policyTypes"
	KEY_INGRESS            = "ingress"
	KEY_EGRESS             = "egress"
	KEY_FROM               = "from"
	KEY_TO                 = "to"

	// PodDisruptionBudget.
	KEY_MIN_AVAILABLE   = "minAvailable"
	KEY_MAX_UNAVAILABLE = "maxUnavailable"

	// HorizontalPodAutoscaler.
	KEY_SCALE_TARGET_REF    = "scaleTargetRef"
	KEY_MIN_REPLICAS        = "minReplicas"
	KEY_MAX_REPLICAS        = "maxReplicas"
	KEY_METRICS             = "metrics"
	KEY_RESOURCE            = "resource"
	KEY_TARGET              = "target"
	KEY_AVERAGE_UTILIZATION = "averageUtilization"

	// securityContext.
	KEY_SECURITY_CONTEXT      = "securityContext"
	KEY_RUN_AS_NON_ROOT       = "runAsNonRoot"
	KEY_RUN_AS_USER           = "runAsUser"
	KEY_RUN_AS_GROUP          = "runAsGroup"
	KEY_FS_GROUP              = "fsGroup"
	KEY_SECCOMP_PROFILE       = "seccompProfile"
	KEY_ALLOW_PRIV_ESCALATION = "allowPrivilegeEscalation"
	KEY_READ_ONLY_ROOT_FS     = "readOnlyRootFilesystem"
	KEY_PRIVILEGED            = "privileged"
	KEY_CAPABILITIES          = "capabilities"
	KEY_DROP                  = "drop"
)

// replicas is the desired replica count, defaulting to DEFAULT_REPLICAS.
func (s Service) replicas() int {
	if s.Replicas > 0 {
		return s.Replicas
	}
	return DEFAULT_REPLICAS
}

// imageRepository is the default image repo baked into values.yaml. Per-env
// values override it with the full registry path at install time.
func (s Service) imageRepository() string {
	if s.Container.Image != "" {
		return s.Container.Image
	}
	return s.Name
}

// Security posture, resolved from the descriptor. Each accessor inverts its
// field so the zero value is the hardened default — set the field only to relax
// a control. These feed the baked securityContext, never a .Values knob, so an
// environment overlay can't weaken security; only a descriptor change can.

// readOnlyRootFilesystem reports whether the container root filesystem is
// mounted read-only (the default; WritableRootFilesystem opts out).
func (s Service) readOnlyRootFilesystem() bool {
	return !s.WritableRootFilesystem
}

// automountSAToken reports whether the pod mounts its ServiceAccount token
// (off by default; MountServiceAccountToken opts in).
func (s Service) automountSAToken() bool {
	return s.MountServiceAccountToken
}

// runAsUser is the non-root UID (and GID) the pod runs as. A stub for now; a
// descriptor field will override it once images need a specific user.
func (s Service) runAsUser() int {
	return DEFAULT_RUN_AS_UID
}

// containerPort is the port the container listens on (default DEFAULT_PORT).
func (s Service) containerPort() int {
	if s.Container.Port > 0 {
		return s.Container.Port
	}
	return DEFAULT_PORT
}

// livenessPath is the HTTP liveness probe path (default DEFAULT_LIVENESS_PATH).
func (s Service) livenessPath() string {
	if s.Container.LivenessPath != "" {
		return s.Container.LivenessPath
	}
	return DEFAULT_LIVENESS_PATH
}

// readinessPath is the HTTP readiness probe path (default DEFAULT_READINESS_PATH).
func (s Service) readinessPath() string {
	if s.Container.ReadinessPath != "" {
		return s.Container.ReadinessPath
	}
	return DEFAULT_READINESS_PATH
}

// strategyType selects the Deployment update strategy. The default is a rolling
// update; RecreateDuringRollout switches to Recreate (tear down old pods first).
func (s Service) strategyType() string {
	if s.RecreateDuringRollout {
		return STRATEGY_RECREATE
	}
	return STRATEGY_ROLLING
}

// minReplicas is the HPA lower bound, defaulting to DEFAULT_MIN_REPLICAS.
func (a Autoscale) minReplicas() int {
	if a.MinReplicas > 0 {
		return a.MinReplicas
	}
	return DEFAULT_MIN_REPLICAS
}

// cpuTarget is the HPA target CPU utilization %, defaulting to
// DEFAULT_CPU_UTILIZATION.
func (a Autoscale) cpuTarget() int {
	if a.TargetCPUUtilization > 0 {
		return a.TargetCPUUtilization
	}
	return DEFAULT_CPU_UTILIZATION
}

// includeFullname returns the Helm include expression for the chart's fullname.
func (s Service) includeFullname() string {
	return `{{ include "` + s.Name + `.fullname" . }}`
}

// includeLabels returns the include expression for the chart's labels, trimmed
// and re-indented by nindent spaces.
func (s Service) includeLabels(nindent int) string {
	return `{{- include "` + s.Name + `.labels" . | nindent ` + strconv.Itoa(nindent) + ` }}`
}

// includeSelectorLabels returns the include expression for the chart's selector
// labels, trimmed and re-indented by nindent spaces.
func (s Service) includeSelectorLabels(nindent int) string {
	return `{{- include "` + s.Name + `.selectorLabels" . | nindent ` + strconv.Itoa(nindent) + ` }}`
}

// writeValuesBlock emits an optional block that renders only when the values key
// is set: a {{- with .Values.<valuesKey> }} guard, the <header> key, and the
// value merged in via toYaml. header often equals valuesKey (nodeSelector), but
// not always (podAnnotations renders under "annotations").
func writeValuesBlock(y *render.YAML, indent int, valuesKey, header string) {
	y.Line(indent, "{{- with .Values."+valuesKey+" }}")
	y.Line(indent, header+":")
	y.Line(indent+1, "{{- toYaml . | nindent "+strconv.Itoa((indent+1)*2)+" }}")
	y.Line(indent, "{{- end }}")
}

// chartYAML renders Chart.yaml.
func (s Service) chartYAML(version string) string {
	desc := s.Description
	if desc == "" {
		desc = s.Name
	}

	var y render.YAML
	y.Field(0, KEY_API_VERSION, CHART_API_VERSION)
	y.Field(0, KEY_NAME, s.Name)
	y.Field(0, KEY_DESCRIPTION, desc)
	y.Field(0, KEY_TYPE, CHART_TYPE)
	y.Field(0, KEY_VERSION, version)
	y.Field(0, KEY_APP_VERSION, version)
	return y.String()
}

// valuesYAML renders values.yaml — the per-environment configuration surface.
// The generator bakes sensible defaults; Helm fills these in per install.
func (s Service) valuesYAML() string {
	var y render.YAML
	y.Line(0, "# Default values for the "+s.Name+" chart.")
	y.Line(0, "# The chart structure is generated; these are the per-environment")
	y.Line(0, "# knobs Helm fills in at install time.")
	y.Line(0, KEY_REPLICA_COUNT+": "+strconv.Itoa(s.replicas()))
	y.Line(0, "")
	y.Line(0, KEY_IMAGE+":")
	y.Field(1, KEY_REPOSITORY, s.imageRepository())
	y.Field(1, KEY_TAG, "") // empty => defaults to .Chart.AppVersion in the templates
	y.Field(1, KEY_PULL_POLICY, DEFAULT_PULL_POLICY)
	y.Line(0, "")
	y.Line(0, KEY_IMAGE_PULL_SECRETS+": []")
	y.Line(0, "")
	y.Line(0, KEY_RESOURCES+":")
	y.Line(1, KEY_REQUESTS+":")
	y.Field(2, KEY_CPU, DEFAULT_CPU_REQUEST)
	y.Field(2, KEY_MEMORY, DEFAULT_MEM_REQUEST)
	y.Line(1, KEY_LIMITS+":")
	y.Field(2, KEY_CPU, DEFAULT_CPU_LIMIT)
	y.Field(2, KEY_MEMORY, DEFAULT_MEM_LIMIT)
	y.Line(0, "")
	y.Line(0, KEY_POD_ANNOTATIONS+": {}")
	y.Line(0, KEY_NODE_SELECTOR+": {}")
	y.Line(0, KEY_TOLERATIONS+": []")
	y.Line(0, KEY_AFFINITY+": {}")
	return y.String()
}

// helpersTPL renders templates/_helpers.tpl: the standard Helm name/label
// template definitions, scoped by the chart name.
func (s Service) helpersTPL() string {
	selector := `app.kubernetes.io/name: {{ include "NAME.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}`
	if s.LegacySelectorLabels {
		selector = "app: NAME"
	}

	tpl := strings.ReplaceAll(HELPERS_TEMPLATE, PLACEHOLDER_SELECTOR, selector)
	tpl = strings.ReplaceAll(tpl, PLACEHOLDER_NAME, s.Name)
	return tpl
}

// writePodSecurityContext emits the pod-level securityContext into y, with
// "securityContext:" at the given indent. It pins a non-root UID/GID, enforces
// runAsNonRoot, and applies the RuntimeDefault seccomp profile — the pod half of
// the Pod Security Standards "restricted" profile.
func (s Service) writePodSecurityContext(y *render.YAML, indent int) {
	uid := strconv.Itoa(s.runAsUser())
	y.Line(indent, KEY_SECURITY_CONTEXT+":")
	y.Bool(indent+1, KEY_RUN_AS_NON_ROOT, true)
	y.Line(indent+1, KEY_RUN_AS_USER+": "+uid)
	y.Line(indent+1, KEY_RUN_AS_GROUP+": "+uid)
	y.Line(indent+1, KEY_FS_GROUP+": "+uid)
	y.Line(indent+1, KEY_SECCOMP_PROFILE+":")
	y.Field(indent+2, KEY_TYPE, SECCOMP_RUNTIME_DEFAULT)
}

// writeContainerSecurityContext emits the container-level securityContext into
// y, with "securityContext:" at the given indent. It drops all capabilities,
// forbids privilege escalation and privileged mode, and (by default) mounts the
// root filesystem read-only — the container half of the "restricted" profile.
// allowPrivilegeEscalation and readOnlyRootFilesystem come straight from the
// descriptor's hardened-by-default fields.
func (s Service) writeContainerSecurityContext(y *render.YAML, indent int) {
	y.Line(indent, KEY_SECURITY_CONTEXT+":")
	y.Bool(indent+1, KEY_ALLOW_PRIV_ESCALATION, s.AllowPrivilegeEscalation)
	y.Bool(indent+1, KEY_READ_ONLY_ROOT_FS, s.readOnlyRootFilesystem())
	y.Bool(indent+1, KEY_PRIVILEGED, false)
	y.Line(indent+1, KEY_CAPABILITIES+":")
	y.Line(indent+2, KEY_DROP+":")
	y.Line(indent+2, "- "+CAP_ALL)
	y.Line(indent+1, KEY_SECCOMP_PROFILE+":")
	y.Field(indent+2, KEY_TYPE, SECCOMP_RUNTIME_DEFAULT)
}

// writeEnv emits the container's literal environment variables into y, sorted by
// key for deterministic output. Nothing is written when there are none.
func (s Service) writeEnv(y *render.YAML, indent int) {
	if len(s.Container.Env) == 0 {
		return
	}

	keys := make([]string, 0, len(s.Container.Env))
	for k := range s.Container.Env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	y.Line(indent, KEY_ENV+":")
	for _, k := range keys {
		y.Line(indent+1, "- "+KEY_NAME+": "+k)
		y.Field(indent+2, KEY_VALUE, s.Container.Env[k])
	}
}

// writeEnvFrom emits envFrom sources for the container's Secrets and ConfigMaps,
// exposing each one's keys as environment variables. Nothing is written when
// there are none.
func (s Service) writeEnvFrom(y *render.YAML, indent int) {
	if len(s.Container.Secrets) == 0 && len(s.Container.ConfigMaps) == 0 {
		return
	}

	y.Line(indent, KEY_ENV_FROM+":")
	for _, name := range s.Container.Secrets {
		y.Line(indent+1, "- "+KEY_SECRET_REF+":")
		y.Field(indent+3, KEY_NAME, name)
	}
	for _, name := range s.Container.ConfigMaps {
		y.Line(indent+1, "- "+KEY_CONFIGMAP_REF+":")
		y.Field(indent+3, KEY_NAME, name)
	}
}

// deploymentYAML renders templates/deployment.yaml. The manifest structure,
// labels, and securityContext are baked here; per-environment scalars
// (replicas, image, resources, scheduling) stay as .Values references Helm
// fills in at install time. Only the zero-value Kind (Deployment) is emitted
// today; other workload kinds come in a later step.
func (s Service) deploymentYAML() string {
	var y render.YAML

	y.Field(0, KEY_API_VERSION, API_APPS_V1)
	y.Field(0, KEY_KIND, KIND_DEPLOYMENT)
	y.Line(0, KEY_METADATA+":")
	y.Line(1, KEY_NAME+": "+s.includeFullname())
	y.Line(1, KEY_LABELS+":")
	y.Line(2, s.includeLabels(4))

	y.Line(0, KEY_SPEC+":")
	// With an HPA the autoscaler owns the replica count, so a static replicas
	// here would be reset on every upgrade — omit it.
	if s.Autoscale == nil {
		y.Line(1, KEY_REPLICAS+": {{ .Values.replicaCount }}")
	}
	y.Line(1, KEY_STRATEGY+":")
	y.Field(2, KEY_TYPE, s.strategyType())
	y.Line(1, KEY_SELECTOR+":")
	y.Line(2, KEY_MATCH_LABELS+":")
	y.Line(3, s.includeSelectorLabels(6))

	y.Line(1, KEY_TEMPLATE+":")
	y.Line(2, KEY_METADATA+":")
	y.Line(3, KEY_LABELS+":")
	y.Line(4, s.includeSelectorLabels(8))
	writeValuesBlock(&y, 3, KEY_POD_ANNOTATIONS, KEY_ANNOTATIONS)

	y.Line(2, KEY_SPEC+":")
	y.Line(3, KEY_SERVICE_ACCOUNT+": "+s.includeFullname())
	y.Bool(3, KEY_AUTOMOUNT_SA_TOKEN, s.automountSAToken())
	writeValuesBlock(&y, 3, KEY_IMAGE_PULL_SECRETS, KEY_IMAGE_PULL_SECRETS)
	s.writePodSecurityContext(&y, 3)

	y.Line(3, KEY_CONTAINERS+":")
	y.Line(4, "- "+KEY_NAME+": "+s.Name)
	y.Line(5, KEY_IMAGE+`: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"`)
	y.Line(5, KEY_IMAGE_PULL_POLICY+": {{ .Values.image.pullPolicy }}")
	s.writeEnv(&y, 5)
	s.writeEnvFrom(&y, 5)
	y.Line(5, KEY_PORTS+":")
	y.Line(6, "- "+KEY_NAME+": "+PORT_NAME_HTTP)
	y.Line(7, KEY_CONTAINER_PORT+": "+strconv.Itoa(s.containerPort()))
	y.Field(7, KEY_PROTOCOL, PROTOCOL_TCP)
	y.Line(5, KEY_LIVENESS_PROBE+":")
	y.Line(6, KEY_HTTP_GET+":")
	y.Field(7, KEY_PATH, s.livenessPath())
	y.Field(7, KEY_PORT, PORT_NAME_HTTP)
	y.Line(5, KEY_READINESS_PROBE+":")
	y.Line(6, KEY_HTTP_GET+":")
	y.Field(7, KEY_PATH, s.readinessPath())
	y.Field(7, KEY_PORT, PORT_NAME_HTTP)
	y.Line(5, KEY_RESOURCES+":")
	y.Line(6, "{{- toYaml .Values."+KEY_RESOURCES+" | nindent 12 }}")
	s.writeContainerSecurityContext(&y, 5)

	// A read-only root filesystem needs a writable scratch dir for /tmp.
	if s.readOnlyRootFilesystem() {
		y.Line(5, KEY_VOLUME_MOUNTS+":")
		y.Line(6, "- "+KEY_NAME+": "+TMP_VOLUME_NAME)
		y.Field(7, KEY_MOUNT_PATH, TMP_MOUNT_PATH)
	}

	if s.readOnlyRootFilesystem() {
		y.Line(3, KEY_VOLUMES+":")
		y.Line(4, "- "+KEY_NAME+": "+TMP_VOLUME_NAME)
		y.Line(5, KEY_EMPTY_DIR+": {}")
	}

	writeValuesBlock(&y, 3, KEY_NODE_SELECTOR, KEY_NODE_SELECTOR)
	writeValuesBlock(&y, 3, KEY_AFFINITY, KEY_AFFINITY)
	writeValuesBlock(&y, 3, KEY_TOLERATIONS, KEY_TOLERATIONS)

	return y.String()
}

// serviceYAML renders templates/service.yaml: a ClusterIP Service fronting the
// workload. It exposes DEFAULT_SERVICE_PORT and targets the container's named
// "http" port, so the Service tracks the container port without duplicating the
// number. The selector reuses the shared selectorLabels helper.
func (s Service) serviceYAML() string {
	var y render.YAML

	y.Field(0, KEY_API_VERSION, API_CORE_V1)
	y.Field(0, KEY_KIND, KIND_SERVICE)
	y.Line(0, KEY_METADATA+":")
	y.Line(1, KEY_NAME+": "+s.includeFullname())
	y.Line(1, KEY_LABELS+":")
	y.Line(2, s.includeLabels(4))

	y.Line(0, KEY_SPEC+":")
	y.Field(1, KEY_TYPE, SERVICE_TYPE_CLUSTERIP)
	y.Line(1, KEY_PORTS+":")
	y.Line(2, "- "+KEY_NAME+": "+PORT_NAME_HTTP)
	y.Line(3, KEY_PORT+": "+strconv.Itoa(DEFAULT_SERVICE_PORT))
	y.Field(3, KEY_TARGET_PORT, PORT_NAME_HTTP)
	y.Field(3, KEY_PROTOCOL, PROTOCOL_TCP)
	y.Line(1, KEY_SELECTOR+":")
	y.Line(2, s.includeSelectorLabels(4))

	return y.String()
}

// serviceaccountYAML renders templates/serviceaccount.yaml. The token is not
// automounted by default (MountServiceAccountToken opts in).
func (s Service) serviceaccountYAML() string {
	var y render.YAML

	y.Field(0, KEY_API_VERSION, API_CORE_V1)
	y.Field(0, KEY_KIND, KIND_SERVICEACCOUNT)
	y.Line(0, KEY_METADATA+":")
	y.Line(1, KEY_NAME+": "+s.includeFullname())
	y.Line(1, KEY_LABELS+":")
	y.Line(2, s.includeLabels(4))
	y.Bool(0, KEY_AUTOMOUNT_SA_TOKEN, s.automountSAToken())

	return y.String()
}

// networkPolicyYAML renders templates/networkpolicy.yaml: a default-deny policy
// scoped to this workload's pods. Ingress and egress are denied by default;
// egress to the cluster DNS (port 53) is always allowed so name resolution keeps
// working, and AllowSameNamespace opens same-namespace traffic both directions.
// Only called when s.NetworkPolicy is non-nil.
func (s Service) networkPolicyYAML() string {
	allowSameNS := s.NetworkPolicy.AllowSameNamespace
	dnsPort := strconv.Itoa(DNS_PORT)
	var y render.YAML

	y.Field(0, KEY_API_VERSION, API_NETWORKING_V1)
	y.Field(0, KEY_KIND, KIND_NETWORKPOLICY)
	y.Line(0, KEY_METADATA+":")
	y.Line(1, KEY_NAME+": "+s.includeFullname())
	y.Line(1, KEY_LABELS+":")
	y.Line(2, s.includeLabels(4))

	y.Line(0, KEY_SPEC+":")
	y.Line(1, KEY_POD_SELECTOR+":")
	y.Line(2, KEY_MATCH_LABELS+":")
	y.Line(3, s.includeSelectorLabels(6))
	y.Line(1, KEY_POLICY_TYPES+":")
	y.Line(2, "- "+POLICY_TYPE_INGRESS)
	y.Line(2, "- "+POLICY_TYPE_EGRESS)

	// Ingress: default-deny (no rules). Optionally allow same-namespace pods.
	if allowSameNS {
		y.Line(1, KEY_INGRESS+":")
		y.Line(2, "- "+KEY_FROM+":")
		y.Line(4, "- "+KEY_POD_SELECTOR+": {}")
	}

	// Egress: default-deny. Same-namespace (optional) precedes the always-on DNS
	// allow.
	y.Line(1, KEY_EGRESS+":")
	if allowSameNS {
		y.Line(2, "- "+KEY_TO+":")
		y.Line(4, "- "+KEY_POD_SELECTOR+": {}")
	}
	y.Line(2, "- "+KEY_TO+":")
	y.Line(4, "- "+KEY_NAMESPACE_SELECTOR+": {}")
	y.Line(3, KEY_PORTS+":")
	y.Line(4, "- "+KEY_PROTOCOL+": "+PROTOCOL_UDP)
	y.Line(5, KEY_PORT+": "+dnsPort)
	y.Line(4, "- "+KEY_PROTOCOL+": "+PROTOCOL_TCP)
	y.Line(5, KEY_PORT+": "+dnsPort)

	return y.String()
}

// podDisruptionBudgetYAML renders templates/poddisruptionbudget.yaml. It emits
// exactly one bound: maxUnavailable when set, otherwise minAvailable (defaulting
// to DEFAULT_MIN_AVAILABLE). Values pass through verbatim so a count renders as a
// YAML int and a percentage ("50%") as a YAML string, both valid intOrString.
// Only called when s.PodDisruptionBudget is non-nil (and validated).
func (s Service) podDisruptionBudgetYAML() string {
	pdb := s.PodDisruptionBudget
	var y render.YAML

	y.Field(0, KEY_API_VERSION, API_POLICY_V1)
	y.Field(0, KEY_KIND, KIND_PDB)
	y.Line(0, KEY_METADATA+":")
	y.Line(1, KEY_NAME+": "+s.includeFullname())
	y.Line(1, KEY_LABELS+":")
	y.Line(2, s.includeLabels(4))

	y.Line(0, KEY_SPEC+":")
	if pdb.MaxUnavailable != "" {
		y.Line(1, KEY_MAX_UNAVAILABLE+": "+pdb.MaxUnavailable)
	} else {
		minAvailable := pdb.MinAvailable
		if minAvailable == "" {
			minAvailable = DEFAULT_MIN_AVAILABLE
		}
		y.Line(1, KEY_MIN_AVAILABLE+": "+minAvailable)
	}
	y.Line(1, KEY_SELECTOR+":")
	y.Line(2, KEY_MATCH_LABELS+":")
	y.Line(3, s.includeSelectorLabels(6))

	return y.String()
}

// writeResourceMetric emits one autoscaling/v2 Resource metric (cpu or memory)
// targeting an average utilization percentage.
func writeResourceMetric(y *render.YAML, indent int, resource string, target int) {
	y.Line(indent, "- "+KEY_TYPE+": "+METRIC_TYPE_RESOURCE)
	y.Line(indent+1, KEY_RESOURCE+":")
	y.Field(indent+2, KEY_NAME, resource)
	y.Line(indent+2, KEY_TARGET+":")
	y.Field(indent+3, KEY_TYPE, HPA_TARGET_UTILIZATION)
	y.Line(indent+3, KEY_AVERAGE_UTILIZATION+": "+strconv.Itoa(target))
}

// autoscaleYAML renders templates/hpa.yaml: a HorizontalPodAutoscaler targeting
// this chart's Deployment. It always emits a CPU metric and adds a memory metric
// when TargetMemoryUtilization is set. Only called when s.Autoscale is non-nil
// (and validated).
func (s Service) autoscaleYAML() string {
	a := s.Autoscale
	fullname := s.includeFullname()
	var y render.YAML

	y.Field(0, KEY_API_VERSION, API_AUTOSCALING_V2)
	y.Field(0, KEY_KIND, KIND_HPA)
	y.Line(0, KEY_METADATA+":")
	y.Line(1, KEY_NAME+": "+fullname)
	y.Line(1, KEY_LABELS+":")
	y.Line(2, s.includeLabels(4))

	y.Line(0, KEY_SPEC+":")
	y.Line(1, KEY_SCALE_TARGET_REF+":")
	y.Field(2, KEY_API_VERSION, API_APPS_V1)
	y.Field(2, KEY_KIND, KIND_DEPLOYMENT)
	y.Line(2, KEY_NAME+": "+fullname)
	y.Line(1, KEY_MIN_REPLICAS+": "+strconv.Itoa(a.minReplicas()))
	y.Line(1, KEY_MAX_REPLICAS+": "+strconv.Itoa(a.MaxReplicas))
	y.Line(1, KEY_METRICS+":")
	writeResourceMetric(&y, 2, RESOURCE_CPU, a.cpuTarget())
	if a.TargetMemoryUtilization > 0 {
		writeResourceMetric(&y, 2, RESOURCE_MEMORY, a.TargetMemoryUtilization)
	}

	return y.String()
}
