package charts

import (
	"strconv"
	"strings"

	"github.com/pskshksh/pod-go-helm-factory/sdk/render"
)

const (
	// Chart.yaml
	CHART_API_VERSION = "v2"
	CHART_TYPE        = "application"

	// values.yaml defaults
	DEFAULT_REPLICAS    = 1
	DEFAULT_PULL_POLICY = "IfNotPresent"
	DEFAULT_CPU_REQUEST = "50m"
	DEFAULT_MEM_REQUEST = "64Mi"
	DEFAULT_CPU_LIMIT   = "500m"
	DEFAULT_MEM_LIMIT   = "256Mi"

	// Security defaults. The container runs as this non-root UID/GID unless a
	// descriptor later overrides it. Zero would be root, so this must be non-zero.
	DEFAULT_RUN_AS_UID = 10001

	// Container/probe defaults.
	DEFAULT_PORT           = 8080
	DEFAULT_LIVENESS_PATH  = "/healthz"
	DEFAULT_READINESS_PATH = "/readyz"

	// Service default. The ClusterIP Service listens here and targets the
	// container's named "http" port, so this can differ from the container port.
	DEFAULT_SERVICE_PORT = 80

	// Deployment rollout strategies.
	STRATEGY_ROLLING  = "RollingUpdate"
	STRATEGY_RECREATE = "Recreate"

	// _helpers.tpl substitution placeholders
	PLACEHOLDER_NAME     = "NAME"
	PLACEHOLDER_SELECTOR = "SELECTOR"

	// HELPERS_TEMPLATE is the templates/_helpers.tpl body. PLACEHOLDER_NAME and
	// PLACEHOLDER_SELECTOR are substituted per chart by helpersTPL.
	HELPERS_TEMPLATE = `{{/* Generated by pod-go-helm-factory. DO NOT EDIT. */}}

{{- define "NAME.name" -}}
NAME
{{- end -}}

{{- define "NAME.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name "NAME" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "NAME.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "NAME.labels" -}}
helm.sh/chart: {{ include "NAME.chart" . }}
{{ include "NAME.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- end -}}

{{- define "NAME.selectorLabels" -}}
SELECTOR
{{- end -}}
`
)

// replicas is the desired replica count, defaulting to DEFAULT_REPLICAS.
func (s Service) replicas() int {
	if s.Replicas > 0 {
		return s.Replicas
	}
	return DEFAULT_REPLICAS
}

// imageRepository is the default image repo baked into values.yaml. Per-env
// values override it with the full registry path at install time.
func (s Service) imageRepository() string {
	if s.Container.Image != "" {
		return s.Container.Image
	}
	return s.Name
}

// Security posture, resolved from the descriptor. Each accessor inverts its
// field so the zero value is the hardened default — set the field only to relax
// a control. These feed the baked securityContext, never a .Values knob, so an
// environment overlay can't weaken security; only a descriptor change can.

// readOnlyRootFilesystem reports whether the container root filesystem is
// mounted read-only (the default; WritableRootFilesystem opts out).
func (s Service) readOnlyRootFilesystem() bool {
	return !s.WritableRootFilesystem
}

// automountSAToken reports whether the pod mounts its ServiceAccount token
// (off by default; MountServiceAccountToken opts in).
func (s Service) automountSAToken() bool {
	return s.MountServiceAccountToken
}

// runAsUser is the non-root UID (and GID) the pod runs as. A stub for now; a
// descriptor field will override it once images need a specific user.
func (s Service) runAsUser() int {
	return DEFAULT_RUN_AS_UID
}

// containerPort is the port the container listens on (default DEFAULT_PORT).
func (s Service) containerPort() int {
	if s.Container.Port > 0 {
		return s.Container.Port
	}
	return DEFAULT_PORT
}

// livenessPath is the HTTP liveness probe path (default DEFAULT_LIVENESS_PATH).
func (s Service) livenessPath() string {
	if s.Container.LivenessPath != "" {
		return s.Container.LivenessPath
	}
	return DEFAULT_LIVENESS_PATH
}

// readinessPath is the HTTP readiness probe path (default DEFAULT_READINESS_PATH).
func (s Service) readinessPath() string {
	if s.Container.ReadinessPath != "" {
		return s.Container.ReadinessPath
	}
	return DEFAULT_READINESS_PATH
}

// strategyType selects the Deployment update strategy. The default is a rolling
// update; RecreateDuringRollout switches to Recreate (tear down old pods first).
func (s Service) strategyType() string {
	if s.RecreateDuringRollout {
		return STRATEGY_RECREATE
	}
	return STRATEGY_ROLLING
}

// chartYAML renders Chart.yaml.
func (s Service) chartYAML(version string) string {
	desc := s.Description
	if desc == "" {
		desc = s.Name
	}

	var y render.YAML
	y.Field(0, "apiVersion", CHART_API_VERSION)
	y.Field(0, "name", s.Name)
	y.Field(0, "description", desc)
	y.Field(0, "type", CHART_TYPE)
	y.Field(0, "version", version)
	y.Field(0, "appVersion", version)
	return y.String()
}

// valuesYAML renders values.yaml — the per-environment configuration surface.
// The generator bakes sensible defaults; Helm fills these in per install.
func (s Service) valuesYAML() string {
	var y render.YAML
	y.Line(0, "# Default values for the "+s.Name+" chart.")
	y.Line(0, "# The chart structure is generated; these are the per-environment")
	y.Line(0, "# knobs Helm fills in at install time.")
	y.Line(0, "replicaCount: "+strconv.Itoa(s.replicas()))
	y.Line(0, "")
	y.Line(0, "image:")
	y.Field(1, "repository", s.imageRepository())
	y.Field(1, "tag", "") // empty => defaults to .Chart.AppVersion in the templates
	y.Field(1, "pullPolicy", DEFAULT_PULL_POLICY)
	y.Line(0, "")
	y.Line(0, "imagePullSecrets: []")
	y.Line(0, "")
	y.Line(0, "resources:")
	y.Line(1, "requests:")
	y.Field(2, "cpu", DEFAULT_CPU_REQUEST)
	y.Field(2, "memory", DEFAULT_MEM_REQUEST)
	y.Line(1, "limits:")
	y.Field(2, "cpu", DEFAULT_CPU_LIMIT)
	y.Field(2, "memory", DEFAULT_MEM_LIMIT)
	y.Line(0, "")
	y.Line(0, "podAnnotations: {}")
	y.Line(0, "nodeSelector: {}")
	y.Line(0, "tolerations: []")
	y.Line(0, "affinity: {}")
	return y.String()
}

// helpersTPL renders templates/_helpers.tpl: the standard Helm name/label
// template definitions, scoped by the chart name.
func (s Service) helpersTPL() string {
	selector := `app.kubernetes.io/name: {{ include "NAME.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}`
	if s.LegacySelectorLabels {
		selector = "app: NAME"
	}

	tpl := strings.ReplaceAll(HELPERS_TEMPLATE, PLACEHOLDER_SELECTOR, selector)
	tpl = strings.ReplaceAll(tpl, PLACEHOLDER_NAME, s.Name)
	return tpl
}

// writePodSecurityContext emits the pod-level securityContext into y, with
// "securityContext:" at the given indent. It pins a non-root UID/GID, enforces
// runAsNonRoot, and applies the RuntimeDefault seccomp profile — the pod half of
// the Pod Security Standards "restricted" profile.
func (s Service) writePodSecurityContext(y *render.YAML, indent int) {
	uid := strconv.Itoa(s.runAsUser())
	y.Line(indent, "securityContext:")
	y.Bool(indent+1, "runAsNonRoot", true)
	y.Line(indent+1, "runAsUser: "+uid)
	y.Line(indent+1, "runAsGroup: "+uid)
	y.Line(indent+1, "fsGroup: "+uid)
	y.Line(indent+1, "seccompProfile:")
	y.Field(indent+2, "type", "RuntimeDefault")
}

// writeContainerSecurityContext emits the container-level securityContext into
// y, with "securityContext:" at the given indent. It drops all capabilities,
// forbids privilege escalation and privileged mode, and (by default) mounts the
// root filesystem read-only — the container half of the "restricted" profile.
// allowPrivilegeEscalation and readOnlyRootFilesystem come straight from the
// descriptor's hardened-by-default fields.
func (s Service) writeContainerSecurityContext(y *render.YAML, indent int) {
	y.Line(indent, "securityContext:")
	y.Bool(indent+1, "allowPrivilegeEscalation", s.AllowPrivilegeEscalation)
	y.Bool(indent+1, "readOnlyRootFilesystem", s.readOnlyRootFilesystem())
	y.Bool(indent+1, "privileged", false)
	y.Line(indent+1, "capabilities:")
	y.Line(indent+2, "drop:")
	y.Line(indent+2, "- ALL")
	y.Line(indent+1, "seccompProfile:")
	y.Field(indent+2, "type", "RuntimeDefault")
}

// deploymentYAML renders templates/deployment.yaml. The manifest structure,
// labels, and securityContext are baked here; per-environment scalars
// (replicas, image, resources, scheduling) stay as .Values references Helm
// fills in at install time. Only the zero-value Kind (Deployment) is emitted
// today; other workload kinds come in a later step.
func (s Service) deploymentYAML() string {
	name := s.Name
	var y render.YAML

	y.Field(0, "apiVersion", "apps/v1")
	y.Field(0, "kind", "Deployment")
	y.Line(0, "metadata:")
	y.Line(1, `name: {{ include "`+name+`.fullname" . }}`)
	y.Line(1, "labels:")
	y.Line(2, `{{- include "`+name+`.labels" . | nindent 4 }}`)

	y.Line(0, "spec:")
	y.Line(1, "replicas: {{ .Values.replicaCount }}")
	y.Line(1, "strategy:")
	y.Field(2, "type", s.strategyType())
	y.Line(1, "selector:")
	y.Line(2, "matchLabels:")
	y.Line(3, `{{- include "`+name+`.selectorLabels" . | nindent 6 }}`)

	y.Line(1, "template:")
	y.Line(2, "metadata:")
	y.Line(3, "labels:")
	y.Line(4, `{{- include "`+name+`.selectorLabels" . | nindent 8 }}`)
	y.Line(3, "{{- with .Values.podAnnotations }}")
	y.Line(3, "annotations:")
	y.Line(4, "{{- toYaml . | nindent 8 }}")
	y.Line(3, "{{- end }}")

	y.Line(2, "spec:")
	y.Line(3, `serviceAccountName: {{ include "`+name+`.fullname" . }}`)
	y.Bool(3, "automountServiceAccountToken", s.automountSAToken())
	y.Line(3, "{{- with .Values.imagePullSecrets }}")
	y.Line(3, "imagePullSecrets:")
	y.Line(4, "{{- toYaml . | nindent 8 }}")
	y.Line(3, "{{- end }}")
	s.writePodSecurityContext(&y, 3)

	y.Line(3, "containers:")
	y.Line(4, "- name: "+name)
	y.Line(5, `image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"`)
	y.Line(5, "imagePullPolicy: {{ .Values.image.pullPolicy }}")
	y.Line(5, "ports:")
	y.Line(6, "- name: http")
	y.Line(7, "containerPort: "+strconv.Itoa(s.containerPort()))
	y.Field(7, "protocol", "TCP")
	y.Line(5, "livenessProbe:")
	y.Line(6, "httpGet:")
	y.Field(7, "path", s.livenessPath())
	y.Field(7, "port", "http")
	y.Line(5, "readinessProbe:")
	y.Line(6, "httpGet:")
	y.Field(7, "path", s.readinessPath())
	y.Field(7, "port", "http")
	y.Line(5, "resources:")
	y.Line(6, "{{- toYaml .Values.resources | nindent 12 }}")
	s.writeContainerSecurityContext(&y, 5)

	// A read-only root filesystem needs a writable scratch dir for /tmp.
	if s.readOnlyRootFilesystem() {
		y.Line(5, "volumeMounts:")
		y.Line(6, "- name: tmp")
		y.Field(7, "mountPath", "/tmp")
	}

	if s.readOnlyRootFilesystem() {
		y.Line(3, "volumes:")
		y.Line(4, "- name: tmp")
		y.Line(5, "emptyDir: {}")
	}

	y.Line(3, "{{- with .Values.nodeSelector }}")
	y.Line(3, "nodeSelector:")
	y.Line(4, "{{- toYaml . | nindent 8 }}")
	y.Line(3, "{{- end }}")
	y.Line(3, "{{- with .Values.affinity }}")
	y.Line(3, "affinity:")
	y.Line(4, "{{- toYaml . | nindent 8 }}")
	y.Line(3, "{{- end }}")
	y.Line(3, "{{- with .Values.tolerations }}")
	y.Line(3, "tolerations:")
	y.Line(4, "{{- toYaml . | nindent 8 }}")
	y.Line(3, "{{- end }}")

	return y.String()
}

// serviceYAML renders templates/service.yaml: a ClusterIP Service fronting the
// workload. It exposes DEFAULT_SERVICE_PORT and targets the container's named
// "http" port, so the Service tracks the container port without duplicating the
// number. The selector reuses the shared selectorLabels helper.
func (s Service) serviceYAML() string {
	name := s.Name
	var y render.YAML

	y.Field(0, "apiVersion", "v1")
	y.Field(0, "kind", "Service")
	y.Line(0, "metadata:")
	y.Line(1, `name: {{ include "`+name+`.fullname" . }}`)
	y.Line(1, "labels:")
	y.Line(2, `{{- include "`+name+`.labels" . | nindent 4 }}`)

	y.Line(0, "spec:")
	y.Field(1, "type", "ClusterIP")
	y.Line(1, "ports:")
	y.Line(2, "- name: http")
	y.Line(3, "port: "+strconv.Itoa(DEFAULT_SERVICE_PORT))
	y.Field(3, "targetPort", "http")
	y.Field(3, "protocol", "TCP")
	y.Line(1, "selector:")
	y.Line(2, `{{- include "`+name+`.selectorLabels" . | nindent 4 }}`)

	return y.String()
}

// serviceaccountYAML renders templates/serviceaccount.yaml. The token is not
// automounted by default (MountServiceAccountToken opts in).
func (s Service) serviceaccountYAML() string {
	name := s.Name
	var y render.YAML

	y.Field(0, "apiVersion", "v1")
	y.Field(0, "kind", "ServiceAccount")
	y.Line(0, "metadata:")
	y.Line(1, `name: {{ include "`+name+`.fullname" . }}`)
	y.Line(1, "labels:")
	y.Line(2, `{{- include "`+name+`.labels" . | nindent 4 }}`)
	y.Bool(0, "automountServiceAccountToken", s.automountSAToken())

	return y.String()
}
