package charts

import (
	"strconv"
	"strings"

	"github.com/pskshksh/pod-go-helm-factory/sdk/render"
)

const (
	// Chart.yaml
	CHART_API_VERSION = "v2"
	CHART_TYPE        = "application"

	// values.yaml defaults
	DEFAULT_REPLICAS    = 1
	DEFAULT_PULL_POLICY = "IfNotPresent"
	DEFAULT_CPU_REQUEST = "50m"
	DEFAULT_MEM_REQUEST = "64Mi"
	DEFAULT_CPU_LIMIT   = "500m"
	DEFAULT_MEM_LIMIT   = "256Mi"

	// Security defaults. The container runs as this non-root UID/GID unless a
	// descriptor later overrides it. Zero would be root, so this must be non-zero.
	DEFAULT_RUN_AS_UID = 10001

	// _helpers.tpl substitution placeholders
	PLACEHOLDER_NAME     = "NAME"
	PLACEHOLDER_SELECTOR = "SELECTOR"

	// HELPERS_TEMPLATE is the templates/_helpers.tpl body. PLACEHOLDER_NAME and
	// PLACEHOLDER_SELECTOR are substituted per chart by helpersTPL.
	HELPERS_TEMPLATE = `{{/* Generated by pod-go-helm-factory. DO NOT EDIT. */}}

{{- define "NAME.name" -}}
NAME
{{- end -}}

{{- define "NAME.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name "NAME" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "NAME.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "NAME.labels" -}}
helm.sh/chart: {{ include "NAME.chart" . }}
{{ include "NAME.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- end -}}

{{- define "NAME.selectorLabels" -}}
SELECTOR
{{- end -}}
`
)

// replicas is the desired replica count, defaulting to DEFAULT_REPLICAS.
func (s Service) replicas() int {
	if s.Replicas > 0 {
		return s.Replicas
	}
	return DEFAULT_REPLICAS
}

// imageRepository is the default image repo baked into values.yaml. Per-env
// values override it with the full registry path at install time.
func (s Service) imageRepository() string {
	if s.Container.Image != "" {
		return s.Container.Image
	}
	return s.Name
}

// Security posture, resolved from the descriptor. Each accessor inverts its
// field so the zero value is the hardened default — set the field only to relax
// a control. These feed the baked securityContext, never a .Values knob, so an
// environment overlay can't weaken security; only a descriptor change can.

// readOnlyRootFilesystem reports whether the container root filesystem is
// mounted read-only (the default; WritableRootFilesystem opts out).
func (s Service) readOnlyRootFilesystem() bool {
	return !s.WritableRootFilesystem
}

// automountSAToken reports whether the pod mounts its ServiceAccount token
// (off by default; MountServiceAccountToken opts in).
func (s Service) automountSAToken() bool {
	return s.MountServiceAccountToken
}

// runAsUser is the non-root UID (and GID) the pod runs as. A stub for now; a
// descriptor field will override it once images need a specific user.
func (s Service) runAsUser() int {
	return DEFAULT_RUN_AS_UID
}

// chartYAML renders Chart.yaml.
func (s Service) chartYAML(version string) string {
	desc := s.Description
	if desc == "" {
		desc = s.Name
	}

	var y render.YAML
	y.Field(0, "apiVersion", CHART_API_VERSION)
	y.Field(0, "name", s.Name)
	y.Field(0, "description", desc)
	y.Field(0, "type", CHART_TYPE)
	y.Field(0, "version", version)
	y.Field(0, "appVersion", version)
	return y.String()
}

// valuesYAML renders values.yaml — the per-environment configuration surface.
// The generator bakes sensible defaults; Helm fills these in per install.
func (s Service) valuesYAML() string {
	var y render.YAML
	y.Line(0, "# Default values for the "+s.Name+" chart.")
	y.Line(0, "# The chart structure is generated; these are the per-environment")
	y.Line(0, "# knobs Helm fills in at install time.")
	y.Line(0, "replicaCount: "+strconv.Itoa(s.replicas()))
	y.Line(0, "")
	y.Line(0, "image:")
	y.Field(1, "repository", s.imageRepository())
	y.Field(1, "tag", "") // empty => defaults to .Chart.AppVersion in the templates
	y.Field(1, "pullPolicy", DEFAULT_PULL_POLICY)
	y.Line(0, "")
	y.Line(0, "imagePullSecrets: []")
	y.Line(0, "")
	y.Line(0, "resources:")
	y.Line(1, "requests:")
	y.Field(2, "cpu", DEFAULT_CPU_REQUEST)
	y.Field(2, "memory", DEFAULT_MEM_REQUEST)
	y.Line(1, "limits:")
	y.Field(2, "cpu", DEFAULT_CPU_LIMIT)
	y.Field(2, "memory", DEFAULT_MEM_LIMIT)
	y.Line(0, "")
	y.Line(0, "podAnnotations: {}")
	y.Line(0, "nodeSelector: {}")
	y.Line(0, "tolerations: []")
	y.Line(0, "affinity: {}")
	return y.String()
}

// helpersTPL renders templates/_helpers.tpl: the standard Helm name/label
// template definitions, scoped by the chart name.
func (s Service) helpersTPL() string {
	selector := `app.kubernetes.io/name: {{ include "NAME.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}`
	if s.LegacySelectorLabels {
		selector = "app: NAME"
	}

	tpl := strings.ReplaceAll(HELPERS_TEMPLATE, PLACEHOLDER_SELECTOR, selector)
	tpl = strings.ReplaceAll(tpl, PLACEHOLDER_NAME, s.Name)
	return tpl
}

// writePodSecurityContext emits the pod-level securityContext into y, with
// "securityContext:" at the given indent. It pins a non-root UID/GID, enforces
// runAsNonRoot, and applies the RuntimeDefault seccomp profile — the pod half of
// the Pod Security Standards "restricted" profile.
func (s Service) writePodSecurityContext(y *render.YAML, indent int) {
	uid := strconv.Itoa(s.runAsUser())
	y.Line(indent, "securityContext:")
	y.Bool(indent+1, "runAsNonRoot", true)
	y.Line(indent+1, "runAsUser: "+uid)
	y.Line(indent+1, "runAsGroup: "+uid)
	y.Line(indent+1, "fsGroup: "+uid)
	y.Line(indent+1, "seccompProfile:")
	y.Field(indent+2, "type", "RuntimeDefault")
}

// writeContainerSecurityContext emits the container-level securityContext into
// y, with "securityContext:" at the given indent. It drops all capabilities,
// forbids privilege escalation and privileged mode, and (by default) mounts the
// root filesystem read-only — the container half of the "restricted" profile.
// allowPrivilegeEscalation and readOnlyRootFilesystem come straight from the
// descriptor's hardened-by-default fields.
func (s Service) writeContainerSecurityContext(y *render.YAML, indent int) {
	y.Line(indent, "securityContext:")
	y.Bool(indent+1, "allowPrivilegeEscalation", s.AllowPrivilegeEscalation)
	y.Bool(indent+1, "readOnlyRootFilesystem", s.readOnlyRootFilesystem())
	y.Bool(indent+1, "privileged", false)
	y.Line(indent+1, "capabilities:")
	y.Line(indent+2, "drop:")
	y.Line(indent+2, "- ALL")
	y.Line(indent+1, "seccompProfile:")
	y.Field(indent+2, "type", "RuntimeDefault")
}
